name: CI/CD Pipeline

on:
  push:
    branches:
      - stagging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./temp-build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Domainesia server using SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          # Hapus semua file di direktori target
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            source /home/vimaname/nodevenv/manajemen-piket/18/bin/activate
            cd /home/vimaname/manajemen-piket
            rm -rf *
          EOF

          # Upload file build ke direktori target
          sshpass -p "${{ secrets.SSH_PASS }}" rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" ./temp-build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/vimaname/manajemen-piket/

          # Jalankan perintah setelah file di-upload
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            source /home/vimaname/nodevenv/manajemen-piket/18/bin/activate
            cd /home/vimaname/manajemen-piket
            mkdir -p tmp
            touch tmp/restart.txt
          EOF
