name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            dist
            package.json
            package-lock.json
            views
            public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./temp-build

      - name: Clear target directory on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            source /home/vimaname/nodevenv/manajemen-piket/18/bin/activate
            cd /home/vimaname/manajemen-piket
            rm -rf *

            - name: Install rsync
            run: sudo apt-get install -y rsync

      - name: Sync build artifacts to server / copy to server's folder
        run: |
          rsync -avz --delete temp-build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/vimaname/manajemen-piket/

      - name: Install dependencies
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            source /home/vimaname/nodevenv/manajemen-piket/18/bin/activate
            cd /home/vimaname/manajemen-piket
            npm install

      - name: Restart node js on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            source /home/vimaname/nodevenv/manajemen-piket/18/bin/activate
            cd /home/vimaname/manajemen-piket
            mkdir -p tmp
            touch tmp/restart.txt
